/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/gameobject.ts" />
/// <reference path="../objects/vector2.ts" />
/// <reference path="../objects/target.ts" />
/// <reference path="../objects/bottle.ts" />
/// <reference path="../objects/ammo.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/game.ts" />
/// <reference path="../scenes/instructions.ts" />
/// <reference path="../scenes/gameover.ts" /> 
//# sourceMappingURL=_reference.js.map